name: Build PKGBUILD (Arch Linux)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: archlinux:latest

    steps:
      - name: Install dependencies for makepkg
        run: |
          pacman -Sy --noconfirm base-devel git

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build package with makepkg
        working-directory: pkg
        run: |
          makepkg -si --noconfirm

      - name: Upload built package
        uses: actions/upload-artifact@v4
        with:
          name: pkg-build
          path: pkg/*.pkg.tar.*
